#!/usr/bin/env node
/* embed-fonts.js - writes arcade/fonts.css with the arcade's pixel fonts embedded as data URLs.
 *   node tools/embed-fonts.js
 * Chrome refuses @font-face files on file:// pages, and a venue may have no network, so the fonts travel inside the CSS.
 * Sources: the latin subsets from Google Fonts in arcade/fonts/ (SIL Open Font License 1.1, see arcade/fonts/OFL-*.txt).
 */
const fs = require('fs');
const path = require('path');
const dir = path.join(__dirname, '..', 'arcade');
const FONTS = [
  { family: 'Press Start 2P', weight: '400', file: 'PressStart2P-latin.woff2' },
  { family: 'Pixelify Sans', weight: '400 700', file: 'PixelifySans-latin.woff2' },
];
const faces = FONTS.map((f) => {
  const b64 = fs.readFileSync(path.join(dir, 'fonts', f.file)).toString('base64');
  return `@font-face { font-family: '${f.family}'; font-style: normal; font-weight: ${f.weight}; font-display: block; src: url(data:font/woff2;base64,${b64}) format('woff2'); }`;
});
const css = `/* Generated by tools/embed-fonts.js from arcade/fonts/*.woff2; do not edit.
 * Press Start 2P: Copyright 2012 The Press Start 2P Project Authors. Pixelify Sans: Copyright 2021 The Pixelify Sans Project Authors.
 * Both under the SIL Open Font License 1.1 (arcade/fonts/OFL-*.txt). Latin subsets from Google Fonts. */
${faces.join('\n')}
`;
fs.writeFileSync(path.join(dir, 'fonts.css'), css);
console.log(`Wrote arcade/fonts.css (${(css.length / 1024).toFixed(1)} KB).`);
